codecov:
  branch: main
  notify:
    wait_for_ci: false

ignore:
  - "test/**"
  - "hack/**"
  - "vendor/**"
  - "Makefile"
  - ".*/**"
  - "*.md"
  - "*.yaml"
  - "*.yml"
  - "*.mod"
  - "*.sum"
  - ".*"

comment:
  layout: "condensed_header, diff, files, flags, components"
  behavior: default
