name: Unit Tests

on:
  pull_request:
    branches: [main]

jobs:
  test:
    name: Unit Tests
    runs-on: arc-runner-set
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v6
      - run: make test
